apps:
  - host: http://app1-host.com
    health_uri: /health
    timeout: 10s
    health_check_cooldown: 60s
    instances:
      - url: http://localhost:8080
      - url: http://localhost:8081
  - host: http://app2-host.com
    health_uri: /api/v2/health
    timeout: 5s
    health_check_cooldown: 45s
    instances:
      - url: http://localhost:9090
      - url: http://localhost:9091